Algoritmo "Tabela verdade"

Var

   i, j: inteiro
   


Inicio
  i <- 11
  j <- 21
     //sim      E   nao = NAO
     //sim      E   sim = SIM
     //nao      E   sim = NAO
     //sim      OU  sim = SIM
     //nao      OU  nao = NAO
     //sim      OU  nao = SIM
  se (i = 10) E (j = 20) entao
  escreval("Fazer Algo")
  senao
  escreval("Nao fazer nada")
  fimse
  
  


Fimalgoritmo