Algoritmo "trabalho com tipos"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 22/05/2022
Var
   numero, numero2, soma, subtracao, multiplicacao : inteiro
   divisao: real
   sucesso: logico


Inicio

      escreval ("N1")
      leia (numero)
      sucesso <- numero > 10
      escreval (sucesso)
Fimalgoritmo